/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UxAnalysisRouteImport } from './routes/ux-analysis'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as QualityScoresRouteImport } from './routes/quality-scores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversionRouteImport } from './routes/conversion'
import { Route as IndexRouteImport } from './routes/index'

const UxAnalysisRoute = UxAnalysisRouteImport.update({
  id: '/ux-analysis',
  path: '/ux-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityScoresRoute = QualityScoresRouteImport.update({
  id: '/quality-scores',
  path: '/quality-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionRoute = ConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversion': typeof ConversionRoute
  '/dashboard': typeof DashboardRoute
  '/quality-scores': typeof QualityScoresRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/trust': typeof TrustRoute
  '/ux-analysis': typeof UxAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversion': typeof ConversionRoute
  '/dashboard': typeof DashboardRoute
  '/quality-scores': typeof QualityScoresRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/trust': typeof TrustRoute
  '/ux-analysis': typeof UxAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversion': typeof ConversionRoute
  '/dashboard': typeof DashboardRoute
  '/quality-scores': typeof QualityScoresRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/trust': typeof TrustRoute
  '/ux-analysis': typeof UxAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversion'
    | '/dashboard'
    | '/quality-scores'
    | '/recommendations'
    | '/reports'
    | '/seo'
    | '/settings'
    | '/trust'
    | '/ux-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversion'
    | '/dashboard'
    | '/quality-scores'
    | '/recommendations'
    | '/reports'
    | '/seo'
    | '/settings'
    | '/trust'
    | '/ux-analysis'
  id:
    | '__root__'
    | '/'
    | '/conversion'
    | '/dashboard'
    | '/quality-scores'
    | '/recommendations'
    | '/reports'
    | '/seo'
    | '/settings'
    | '/trust'
    | '/ux-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversionRoute: typeof ConversionRoute
  DashboardRoute: typeof DashboardRoute
  QualityScoresRoute: typeof QualityScoresRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReportsRoute: typeof ReportsRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  TrustRoute: typeof TrustRoute
  UxAnalysisRoute: typeof UxAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ux-analysis': {
      id: '/ux-analysis'
      path: '/ux-analysis'
      fullPath: '/ux-analysis'
      preLoaderRoute: typeof UxAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-scores': {
      id: '/quality-scores'
      path: '/quality-scores'
      fullPath: '/quality-scores'
      preLoaderRoute: typeof QualityScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion': {
      id: '/conversion'
      path: '/conversion'
      fullPath: '/conversion'
      preLoaderRoute: typeof ConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversionRoute: ConversionRoute,
  DashboardRoute: DashboardRoute,
  QualityScoresRoute: QualityScoresRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReportsRoute: ReportsRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  TrustRoute: TrustRoute,
  UxAnalysisRoute: UxAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
